-- Migration: 0026_insertar_musculos
-- Objetivo: Insertar catalogo de musculos desde musculos.json

insert into public.musculos (nombre)
values
  ('abdomen'),
  ('abdomen inferior'),
  ('abdominales'),
  ('abductores'),
  ('aductores'),
  ('antebrazos'),
  ('braquial'),
  ('braquiorradial'),
  ('bíceps'),
  ('columna'),
  ('coracobraquial'),
  ('core'),
  ('cuádriceps'),
  ('deltoides'),
  ('deltoides anterior'),
  ('deltoides anteriores'),
  ('deltoides medio'),
  ('deltoides posteriores'),
  ('dorsal ancho'),
  ('dorsales'),
  ('elevador de la escápula'),
  ('espalda'),
  ('espalda alta'),
  ('estabilizadores de tobillo'),
  ('esternocleidomastoideo'),
  ('extensores de muñeca'),
  ('flexores de la cadera'),
  ('flexores de muñeca'),
  ('gemelos'),
  ('glúteo mayor'),
  ('glúteo medio'),
  ('glúteos'),
  ('hombros'),
  ('ingle'),
  ('isquiotibiales'),
  ('manguito rotador'),
  ('manos'),
  ('muñecas'),
  ('músculos de agarre'),
  ('oblicuos'),
  ('parte interna del muslo'),
  ('pecho'),
  ('pecho superior'),
  ('pectorales'),
  ('pectíneo'),
  ('pies'),
  ('redondo mayor'),
  ('redondo menor'),
  ('romboides'),
  ('serrato anterior'),
  ('sistema cardiovascular'),
  ('supraespinoso'),
  ('sóleo'),
  ('tensor de la fascia lata'),
  ('tibial anterior'),
  ('tibiales'),
  ('tobillos'),
  ('trapecios'),
  ('tríceps'),
  ('zona lumbar')
on conflict (nombre) do nothing;

