-- Migration: 0035_insertar_musculos_final
-- Objetivo: Insertar 93 musculos del dataset final

insert into public.musculos (nombre) values
  ('Abductores'),
  ('Aductores'),
  ('Aductores del muslo'),
  ('Antebrazos'),
  ('Braquial'),
  ('Braquial anterior'),
  ('Braquiorradial'),
  ('Bíceps'),
  ('Bíceps braquial'),
  ('Coracobraquial'),
  ('Core'),
  ('Core (como estabilizador)'),
  ('Cuadrado lumbar'),
  ('Cuádriceps'),
  ('Deltoides'),
  ('Deltoides anterior'),
  ('Deltoides medio'),
  ('Deltoides posterior'),
  ('Dorsal ancho'),
  ('Elevador de la escápula'),
  ('Erectores espinales'),
  ('Erectores espinales torácicos'),
  ('Escalenos'),
  ('Estabilizadores de la escápula'),
  ('Estabilizadores globales'),
  ('Esternocleidomastoideo'),
  ('Extensor radial corto del carpo'),
  ('Extensor radial largo del carpo'),
  ('Extensores de la muñeca'),
  ('Extensores de los dedos'),
  ('Extensores de muñeca'),
  ('Extensores del antebrazo'),
  ('Flexores de antebrazo'),
  ('Flexores de cadera'),
  ('Flexores de la muñeca'),
  ('Flexores de los dedos'),
  ('Flexores de muñeca'),
  ('Flexores del antebrazo'),
  ('Gastrocnemio'),
  ('Gemelos'),
  ('Glúteo mayor'),
  ('Glúteo medio'),
  ('Glúteos'),
  ('Grupo muscular objetivo del estiramiento'),
  ('Grupo muscular principal'),
  ('Hombros'),
  ('Iliopsoas'),
  ('Isquiosurales'),
  ('Isquiotibiales'),
  ('Manguito rotador'),
  ('Movilidad articular'),
  ('Multífidos'),
  ('Músculos intrínsecos de la mano'),
  ('Músculos intrínsecos del pie'),
  ('Músculos paravertebrales'),
  ('Oblicuo externo'),
  ('Oblicuo interno'),
  ('Oblicuos'),
  ('Pantorrillas'),
  ('Pectoral'),
  ('Pectoral mayor'),
  ('Pectoral mayor (clavicular)'),
  ('Pectoral mayor (porción clavicular)'),
  ('Pectoral mayor (porción inferior)'),
  ('Pectoral menor'),
  ('Piernas'),
  ('Psoas ilíaco'),
  ('Recto abdominal'),
  ('Recto abdominal inferior'),
  ('Recto abdominal superior'),
  ('Recto femoral'),
  ('Redondo mayor'),
  ('Romboides'),
  ('Romboides mayor'),
  ('Romboides menor'),
  ('Sartorio'),
  ('Serrato anterior'),
  ('Suelo pélvico'),
  ('Supraespinoso'),
  ('Sóleo'),
  ('Tejido conectivo'),
  ('Tensor de la fascia lata'),
  ('Tibial anterior'),
  ('Tibial posterior'),
  ('Transverso abdominal'),
  ('Trapecio'),
  ('Trapecio inferior'),
  ('Trapecio medio'),
  ('Trapecio superior'),
  ('Tríceps'),
  ('Tríceps braquial'),
  ('Tríceps braquial (cabeza larga)'),
  ('Tríceps braquial (énfasis en la cabeza larga)')
on conflict (nombre) do nothing;
