-- Migration: 0037_insertar_equipamientos_final
-- Objetivo: Insertar 74 equipamientos del dataset final

insert into public.equipamientos (nombre) values
  ('Agarre de cuerda'),
  ('Agarre de mano simple'),
  ('Agarre estrecho neutro'),
  ('Almohadilla protectora'),
  ('Anillas'),
  ('Asistencia'),
  ('Balón medicinal'),
  ('Banco'),
  ('Banco (opcional para soporte)'),
  ('Banco declinado'),
  ('Banco inclinado'),
  ('Banco o silla'),
  ('Banco plano'),
  ('Banco predicador'),
  ('Banco regulable'),
  ('Banda de resistencia'),
  ('Banda de resistencia tubular'),
  ('Banda elástica'),
  ('Barra'),
  ('Barra de dominadas'),
  ('Barra ez'),
  ('Barra fija'),
  ('Barra larga'),
  ('Barra recta'),
  ('Barra recta de polea'),
  ('Barra vertical'),
  ('Barras paralelas'),
  ('Barras paralelas bajas'),
  ('Battle ropes'),
  ('Bicicleta estática'),
  ('Cajón'),
  ('Cajón pliométrico'),
  ('Cinta rodante'),
  ('Cinturón de lastre'),
  ('Colchoneta'),
  ('Comba'),
  ('Cuerda de tríceps'),
  ('Disco'),
  ('Discos de pesas'),
  ('Déficit o escalón'),
  ('Ergómetro de remo'),
  ('Escalera'),
  ('Escalera de agilidad'),
  ('Escalón'),
  ('Fitball'),
  ('Foam roller'),
  ('Kettlebell'),
  ('Landmine'),
  ('Lastre'),
  ('Mancuerna'),
  ('Mancuernas'),
  ('Maneral de agarre estrecho (triángulo o v-bar)'),
  ('Máquina de palanca'),
  ('Máquina de poleas'),
  ('Máquina de prensa de piernas'),
  ('Máquina de prensa de piernas a 45°'),
  ('Máquina elíptica'),
  ('Máquina escaladora'),
  ('Máquina smith'),
  ('Pared'),
  ('Peso corporal'),
  ('Polea'),
  ('Rack de sentadillas'),
  ('Rodillo de espuma'),
  ('Rodillo de muñeca'),
  ('Silla'),
  ('Sillas'),
  ('Sin equipamiento'),
  ('Soporte'),
  ('Soporte de banca'),
  ('Suelo'),
  ('Superficie elevada'),
  ('Suspensión'),
  ('Toalla')
on conflict (nombre) do nothing;
